- name: create site folder
  file:
      path: /etc/fastd/ff{{ site.name }}
      state: directory

- name: fastd.conf
  template:
      src: fastd.conf
      dest: /etc/fastd/ff{{ site.name }}/fastd.conf
      mode: 0640

- name: add fastd bin folder
  file:
      path: /etc/fastd/ff{{ site.name }}/bin
      state: directory

- name: add fastd up script
  template:
      src: fastd_up.sh
      dest: /etc/fastd/ff{{ site.name }}/bin/up.sh
      mode: 0744

- name: add fastd peers folder
  file:
      path: /etc/fastd/ff{{ site.name }}/peers
      state: directory

- name: add fastd peer gw configs
  template:
    src: peer_conf
    dest: /etc/fastd/ff{{ site.name }}/peers/gateway
    mode: 0640

- name: start and enable fastd service
  systemd:
      name: fastd@ff{{ site.name }}.service
      enabled: yes
      state: started

