# used to install a yanic with a meshviewer on nginx
# Recommended: install on a backend server and add a reverse proxy in front of
- name: setup map
  hosts: map
  user: root
  roles:
    - update_ssh_keys
    - configure_sshd
    - upgrade_server
    - install_batman
    #- install_fastd
    - install_wireguard
    - install_wireguard_mesh_map
    #- configure_fastd_map
    - install_yanic
    - install_meshviewer
    - install_admin_packages
    - install_influxdb
