- name: setup fastds
  hosts: fastd
  user: root
  roles:
      - update_ssh_keys
      - upgrade_server
      - configure_journald
      - configure_sysctl
      - configure_iptables
      - configure_static_routes
      - install_ntp
      - install_haveged
      - install_batman
      - configure_batman_gw
      - install_dhcp
      - install_radvd
      - install_bind
      - install_wireguard
      - install_wireguard_mesh
      - install_wireguard_backbone
      - install_babeld
      - install_fastd
      - configure_fastd_gw
      - install_mesh-announce
      #- install_monitoring
      - install_iperf3
      - install_admin_packages
- name: basic uplink config
  hosts: uplink
  user: root
  roles:
      - update_ssh_keys
      - upgrade_server
      - configure_journald
      - configure_sysctl
      - configure_iptables
      - configure_static_routes
      - install_cronie
      #- install_nginx
      - install_ntp
      - install_haveged
      - install_wireguard
      - install_wireguard_backbone
      - install_babeld
      - install_iperf3
      - install_admin_packages
