- name: install influx
  apt:
    name:
      - influxdb
      - python-requests
      - python-influxdb
    state: present

- name: Create an admin user on influxdb
  community.general.influxdb_user:
    user_name: "{{ influx.admin.username }}"
    user_password: "{{ influx.admin.password }}"
    username: "{{ influx.admin.username }}"
    password: "{{ influx.admin.password }}"
    admin: yes
- name: Create database using custom credentials
  community.general.influxdb_database:
    database_name: "{{ influx.db }}"
    username: "{{ influx.admin.username }}"
    password: "{{ influx.admin.password }}"
- name: Create an freifunk user on influxdb
  community.general.influxdb_user:
    user_name: "{{ influx.username }}"
    user_password: "{{ influx.password }}"
    admin: no
    username: "{{ influx.admin.username }}"
    password: "{{ influx.admin.password }}"
    grants:
      - database: '{{ influx.db }}'
        privilege: 'WRITE'

- name: enable auth
  lineinfile:
    path: /etc/influxdb/influxdb.conf
    regexp: 'auth-enabled ='
    line: '  auth-enabled = true'
  notify: restart influxdb
