---
- name: install linkstat dependencies
  apt:
    name:
      - curl
    state: present
- name: install linkstat
  copy:
    src: "linkstat.sh"
    dest: /usr/local/bin/
    mode: 0755
  notify: restart linkstat
- name: install linkstat service
  template:
    src: linkstat.service
    dest: /etc/systemd/system/linkstat.service
    mode: 0755
  notify: restart linkstat
- name: start and enable linkstat service
  systemd:
    daemon_reload: yes
    name: "linkstat"
    state: started
    enabled: yes