- name: install iptables-persistent
  apt:
      name: iptables-persistent

- name: copy iptables.rules
  template:
      src: iptables.rules
      dest: /etc/iptables/rules.v4

- name: copy ip6tables.rules
  template:
      src: ip6tables.rules
      dest: /etc/iptables/rules.v6
