- name: install bind
  apt:
    name: bind9

- name: create named zone backup folder
  file:
    path: /var/named/bak
    state: directory
    owner: bind
    group: bind

- name: bind config
  template:
      src: named.conf
      dest: /etc/bind/named.conf
  notify: reload bind9
