---
- name: install openvpn
  pacman:
      name: openvpn
      state: present

- name: install ca.crt
  copy:
      src: ca.crt
      dest: /etc/openvpn/client/ca.crt
  notify: restart openvpn

- name: install crl.pem
  copy:
      src: crl.pem
      dest: /etc/openvpn/client/crl.pem
  notify: restart openvpn

- name: install mullvad-up.sh
  copy:
      src: mullvad-up.sh
      dest: /etc/openvpn/client/mullvad-up.sh
      mode: 0744
  notify: restart openvpn

- name: install mullvad.conf
  template:
      src: mullvad.conf.j2
      dest: /etc/openvpn/client/mullvad.conf
  notify: restart openvpn

- name: install mullvad.key
  template:
      src: mullvad.key.j2
      dest: /etc/openvpn/client/mullvad.key
  notify: restart openvpn

- name: install mullvad.crt
  template:
      src: mullvad.crt.j2
      dest: /etc/openvpn/client/mullvad.crt
  notify: restart openvpn

- name: create sysetmd openvpn folder
  file:
      path: /etc/systemd/system/openvpn-client@mullvad.service.d
      state: directory

- name: always restart openvpn
  copy:
      src: override.conf
      dest: /etc/systemd/system/openvpn-client@mullvad.service.d/override.conf
      
- name: start and enable openvpn-client@mullvad.service
  systemd:
      name: openvpn-client@mullvad.service
      daemon_reload: yes
      enabled: yes
      state: started
