- name: create wireguard config for sites
  template:
      src: wg.conf
      dest: /etc/wireguard/wg{{ site.name }}.conf
      mode: 0400
  loop: "{{ sites }}"
  loop_control:
    loop_var: site

- name: create wireguard up scripts for sites
  template:
      src: up.sh
      dest: /etc/wireguard/up{{ site.name }}.sh
      mode: 0744
  loop: "{{ sites }}"
  loop_control:
    loop_var: site

- name: create wireguard down scripts for sites
  template:
      src: down.sh
      dest: /etc/wireguard/down{{ site.name }}.sh
      mode: 0744
  loop: "{{ sites }}"
  loop_control:
    loop_var: site

- name: start and enable wireguard mesh
  systemd:
      name: wg-quick@wg{{ site.name }}.service
      enabled: yes
      state: started
  loop: "{{ sites }}"
  loop_control:
    loop_var: site
