- name: install dhcp
  apt:
      name: isc-dhcp-server 
# fastd's up.sh will start dhcpd anyways
# also this still uses init.d and breaks,
# when autostart is enabled
- name: disable dhcpd autostart
  systemd:
      name: isc-dhcp-server
      enabled: no

- name: dhcpd.conf
  template:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
- name: isc-dhcpd-server
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: "^#?INTERFACESv4="
    line: INTERFACESv4="bat{% for site in sites %}{{ site.name }} {% endfor %}"
#  notify: restart dhcpd4
