- name: install dependencies for yanic
  apt:
    name:
      - git
    state: present
- name: install go
  command:
    cmd: |
      cd /usr/local/
      wget https://dl.google.com/go/go1.19.5.linux-amd64.tar.gz -O go-release-linux-amd64.tar.gz
      tar xvf go-release-linux-amd64.tar.gz
      rm go-release-linux-amd64.tar.gz
    creates: /usr/local/go
- name: get yanic package
  shell: go install github.com/FreifunkBremen/yanic@latest
  environment:
    GOPATH: "/opt/go/"
    PATH: "$PATH:/usr/local/go/bin:$GOPATH/bin"

- name: add yanic user
  user:
    name: yanic
    home: /var/lib/yanic
    system: yes

- name: create yanic webserver data folder
  file:
    path: /var/www/html/data
    state: directory
    owner: yanic
    group: yanic
- name: create yanic log file
  file:
    path: /var/log/yanic.log
    state: touch
    owner: yanic
    group: yanic
- name: copy yanic.conf file
  template:
    src: yanic.conf
    dest: /etc/yanic.conf
- name: copy yanic systemd files
  copy:
    src: yanic.service
    dest: /etc/systemd/system/yanic.service
    mode: preserve
- name: start and enable yanic.service
  systemd:
    name: yanic.service
    daemon_reload: yes
    enabled: yes
    state: started