- name: Add WireGuard repository on buster or earlier
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    update_cache: yes
- name: Get architecture
  command: "dpkg --print-architecture"
  register: dpkg_arch
  changed_when: False
- set_fact:
    kernel_header_version: "{{ ('-cloud-' in ansible_kernel) | ternary(ansible_kernel,dpkg_arch.stdout) }}"
- name: Install kernel headers to compile Wireguard with DKMS
  apt:
    name:
      - "linux-headers-{{ kernel_header_version }}"
    state: present
- name: install wireguard
  apt:
    name:
      - 'wireguard'
