- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: set external grafana hostname
  ini_file:
    path: /etc/grafana/grafana.ini
    section: server
    option: domain
    value: "{{ grafana.domain }}"
  notify: restart grafana-server
- name: set grafana url pattern
  ini_file:
    path: /etc/grafana/grafana.ini
    section: server
    option: root_url
    value: "{{ grafana.root_url }}"
  notify: restart grafana-server

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
