- name: install radvd
  apt:
      name: radvd
- name: radvd config
  template:
      src: radvd.conf
      dest: /etc/radvd.conf

- name: start and enable radvd
  systemd:
      name: radvd.service
      enabled: yes
      state: started
