- name: create networkconfig config
  template:
      src: network
      dest: /etc/network/interfaces.d/70-{{ item.name }}
  with_items: "{{ ffrl_peers }}"

- name: install bird
  apt:
      name: bird
      state: present

- name: create bird config
  template:
      src: bird.conf
      dest: /etc/bird.conf
  notify: reload bird

- name: start and enable bird
  systemd:
      name: bird.service
      state: started
      enabled: yes
