- name: create networkconfig config
  template:
      src: network
      dest: /etc/network/interfaces.d/70-{{ item.name }}.cfg
  with_items: "{{ ffrl_peers }}"

- name: start networkconfig config
  shell: ifup {{ item.name }}
  args:
    executable: /bin/bash
  with_items: "{{ ffrl_peers }}"

- name: enable networkconfig config
  systemd:
      name: ifup@{{ item.name }}.service
      enabled: yes
  with_items: "{{ ffrl_peers }}"

- name: install bird
  apt:
      name: bird2
      state: present
- name: creat log datei für bird
  file:
    path: /var/log/bird.log
    state: touch
- name: Change file ownership, group and permissions
  file:
    path: /var/log/bird.log
    owner: bird
    group: bird
- name: create bird config
  template:
      src: bird.conf
      dest: /etc/bird/bird.conf
  notify: reload bird

- name: start and enable bird
  systemd:
      name: bird.service
      state: started
      enabled: yes
