- name: create wireguard config for peers
  template:
      src: wg.conf
      dest: /etc/wireguard/wgbb{{ hostvars[item]['wireguard_bb_name'] }}.conf
      mode: 0400
  with_items:
      - "{{ groups['uplink'] }}"

- name: create wireguard up scripts for peers
  template:
      src: up.sh
      dest: /etc/wireguard/upbb{{ hostvars[item]['wireguard_bb_name'] }}.sh
      mode: 0744
  with_items: 
      - "{{ groups['uplink'] }}"

- name: create wireguard down scripts for peers
  template:
      src: down.sh
      dest: /etc/wireguard/downbb{{ hostvars[item]['wireguard_bb_name'] }}.sh
      mode: 0744
  with_items: 
      - "{{ groups['uplink'] }}"

- name: start and enable wireguard mesh
  systemd:
      name: wgbackbone@{{ hostvars[item]['wireguard_bb_name'] }}.service
      enabled: yes
      state: started
      daemon_reload: yes
  with_items: 
      - "{{ groups['uplink'] }}"
